
name: Running Mocha Chai Solidity Unit Tests
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run mocha and chai tests for solidity on github actions CI
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Mocha Chai Unit Test Action
      uses: EthereumRemix/ts-sol-test@v1.2.0-dev
      with:
        test-path: 'tests'
        contract-path: 'contracts'
        compiler-version: '0.8.7'
